# Generated by Django 3.1.1 on 2020-09-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(max_length=100)),
                ('semester', models.IntegerField(default=0)),
                ('credit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Info2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=200)),
                ('minor', models.CharField(max_length=200)),
                ('elective', models.IntegerField(default=0)),
                ('max_lecture', models.IntegerField(default=0)),
                ('no_class_day', models.CharField(max_length=5)),
            ],
        ),
    ]
